name: Run tests

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
            repository: 'bondarenkokate73/simbirsoft_sdet_project'
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          sleep 15

      - name: "Использование ветки main репозитория"
        uses: actions/checkout@v3
      - name: "Запуск тестов"
        run: mvn clean test
        continue-on-error: true
      - name: "Генерация allure-report"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: target/allure-history

      - name: "Создание ветки gh-pages содержащей allure report"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-history