name: Run tests

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
            repository: 'bondarenkokate73/simbirsoft_sdet_project'
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker (with conflict resolution)
        run: |
          sudo apt-get update
          # Удаляем конфликтующие пакеты, если они есть
          sudo apt-get remove -y containerd || true
          # Устанавливаем Docker с явным указанием версии containerd.io
          sudo apt-get install -y \
            ca-certificates \
            curl \
              gnupg \
              lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          sudo systemctl start docker

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          sleep 15

      - name: "Использование ветки main репозитория"
        uses: actions/checkout@v3
      - name: "Запуск тестов"
        run: mvn clean test
        continue-on-error: true
      - name: "Генерация allure-report"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/allure-report
          allure_history: target/allure-history

      - name: "Создание ветки gh-pages содержащей allure report"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-history